package com.example.vk.user;


public enum ERole {
    ROLE_ADMIN,
    ROLE_POSTS_VIEWERS,
    ROLE_POSTS_EDITORS,
    ROLE_USERS_VIEWERS,
    ROLE_USERS_EDITORS,
    ROLE_ALBUMS_VIEWERS,
    ROLE_ALBUMS_EDITORS
}
